FROM golang:1.25-alpine

WORKDIR /app

RUN go install github.com/air-verse/air@latest
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

COPY go.mod go.sum ./
RUN go mod download

# Run migrations
CMD ["./devserver.sh"]
