stock_code_name_dict = {
    "502": "3Cnergy",
    "NLC": "5E Resources",
    "AZG": "8Telecom",
    "1Y1": "9R",
    "BQC": "A-Smart",
    "BTJ": "A-Sonic Aero",
    "533": "ABR",
    "L5I": "Abterra",
    "541": "Abundance Intl",
    "570": "Abundante",
    "QZG": "Accrelist Ltd",
    "A75": "Ace Achieve Info",
    "5FW": "Acesian Partners",
    "AYV": "Acma",
    "43F": "AcroMeta",
    "A31": "Addvalue Tech",
    "BLZ": "Advanced",
    "5TY": "Advanced Systems",
    "43Q": "Advancer Global",
    "5EF": "Adventus",
    "XVG": "Aedge Group",
    "AWX": "AEM SGD",
    "XWA": "AEM USD",
    "L38": "AF Global",
    "1A4": "AGV",
    "O5RU": "AIMS APAC Reit",
    "BVP": "AIMS Property",
    "40F": "Alita Resources",
    "MIJ": "Alliance HC",
    "A13": "Allied Tech",
    "VVL": "AlphaDX",
    "ZXY": "Alpina Holdings",
    "40V": "Alset",
    "A34": "Amara",
    "S9B": "Amcorp Global",
    "49B": "AMOS Group",
    "AOF": "Amplefield Ltd",
    "HKB": "AMTD IDEA OV",
    "Y35": "AnAn Intl",
    "BTX": "Anchun Intl",
    "A52": "AnnAik",
    "5AL": "Annica",
    "1D4": "Aoxin Q & M",
    "5AU": "AP Oil",
    "5RA": "AP Strategic",
    "CLN": "APAC Realty",
    "XZL": "ARA HTrust USD",
    "YYB": "Arion Ent",
    "A17U": "Ascendas Reit",
    "CY6U": "Ascendas-iTrust",
    "AWG": "Ascent Bridge",
    "HMN": "Ascott Trust",
    "A55": "Asia Enterprises",
    "5RE": "Asia Vets",
    "505": "AsiaMedic",
    "1J3": "Asian Healthcare",
    "585": "Asian Micro",
    "S7OU": "Asian Pay Tv Tr",
    "5WV": "AsiaPhos",
    "5CR": "Asiatic",
    "A04": "ASL Marine",
    "1F3": "Aspen",
    "A30": "Aspial",
    "42S": "Astaka",
    "575": "ASTI",
    "5UL": "Atlantic Nav",
    "1AZ": "Audience",
    "5GJ": "AusGroup",
    "U09": "Avarga",
    "1R6": "Avi-Tech Hldg",
    "A05": "AVJennings A$",
    "42U": "Axington",
    "IXOR": "Axington R",
    "QPQR": "Axington R1",
    "BBW": "Azeus",
    "8AZ": "Aztech Gbl",
    "CJN": "B&M Hldg",
    "BTP": "Baker Technology",
    "B26": "Ban Leong",
    "B58": "Banyan Tree",
    "KJ5": "BBR",
    "BEZ": "Beng Kuang",
    "CGN": "Best World",
    "VFP": "Beverly JCG",
    "BQN": "BH Global",
    "BMGU": "BHG Retail Reit",
    "8YY": "Biolidics",
    "41H": "BlackGoldNatural",
    "5VI": "Boldtek",
    "B28": "Bonvests",
    "F9D": "Boustead",
    "AVM": "Boustead Proj",
    "BEC": "BRC Asia",
    "B69": "Broadway Ind",
    "AWC": "Brook Crompton",
    "B61": "Bukit Sembawang",
    "P8Z": "Bumitama Agri",
    "BTE": "Bund Center",
    "BAC": "Camsing Hc",
    "594": "CapAllianz",
    "1D5": "Capital World",
    "9CI": "CapitaLandInvest",
    "AU8U": "CapLand China T",
    "C38U": "CapLand IntCom T",
    "AWV": "Captii",
    "C04": "Casa",
    "J85": "CDL HTrust",
    "BXE": "CDW",
    "OU8": "Centurion",
    "5EB": "CFM",
    "C13": "CH Offshore",
    "573": "Challenger",
    "5QT": "Charisma Energy",
    "5NV": "Chasen",
    "5TW": "ChasWood Res",
    "C05": "Chemical Ind",
    "G92": "China Aviation",
    "5OU": "China Env",
    "RS1": "China Env Res",
    "U9E": "China Everbright",
    "B0Z": "China Fishery",
    "BEH": "China Intl",
    "BHD": "China Mining",
    "42W": "China Star Food",
    "BCD": "China Yuanbang",
    "P74": "ChinaKangdaFood",
    "GU5": "ChinaKundaTech",
    "QES": "ChinaSunsine",
    "C29": "Chip Eng Seng",
    "42E": "Choo Chiang",
    "C33": "Chuan Hup",
    "C09": "CityDev",
    "P9D": "Civmec",
    "1H3": "Clearbridge",
    "5TP": "CNMC Goldmine",
    "567": "Colex",
    "N0Z": "Combine Will",
    "C52": "ComfortDelGro",
    "P8A": "Cordlife",
    "C41": "Cortina",
    "F83": "COSCO SHP SG",
    "B9S": "CosmoSteel",
    "CIN": "Courage Inv",
    "C76": "Creative",
    "TCU": "CreditBureauAsia",
    "CWBU": "Cromwell Reit EUR",
    "CWCU": "Cromwell Reit SGD",
    "C06": "CSC",
    "544": "CSE Global",
    "DHLU": "Daiwa Hse Log Tr",
    "BLR": "Darco Water Tech",
    "CEDU": "Dasin Retail Tr",
    "BKW": "Datapulse Tech",
    "D05": "DBS",
    "BTF": "Debao Property",
    "D03": "Del Monte Pac",
    "P34": "Delfi",
    "D01": "DFIRG USD",
    "DCRU": "DigiCore Reit USD",
    "BAI": "Digilife Tech",
    "532": "DISA",
    "GRQ": "Don Agro",
    "MT1": "Dragon",
    "5SO": "Duty Free Intl",
    "NO4": "Dyna-Mac",
    "LIW": "Eagle HTrust USD",
    "BWCU": "EC World Reit",
    "EHG": "Econ Healthcare",
    "5CT": "EcoWise",
    "5HG": "Edition",
    "42Z": "Eindec",
    "MXNU": "EliteComREIT GBP",
    "BIX": "Ellipsiz",
    "EMI": "Emperador Inc.",
    "R14": "Eneco Energy",
    "S44": "EnGro",
    "BQD": "Envictus",
    "L23": "Enviro-Hub",
    "5MQ": "Epicentre",
    "5RC": "ES",
    "J91U": "ESR-LOGOS REIT",
    "1C0": "ETC Singapore",
    "5G1": "EuroSports Gbl",
    "BDF": "Excelpoint",
    "5DN": "Ezra",
    "F99": "F & N",
    "5FL": "Falcon Energy",
    "5TJ": "Far East",
    "Q5T": "Far East HTrust",
    "O10": "Far East Orchard",
    "BDU": "Federal Int",
    "5F4": "Figtree",
    "AW9U": "First Reit",
    "EB5": "First Resources",
    "ADN": "First Sponsor",
    "F10": "FJ Benjamin",
    "F03": "Food Empire",
    "8A1": "Forise Int",
    "OAJ": "FortressMinerals",
    "J69U": "Frasers Cpt Tr",
    "ACV": "Frasers HTrust",
    "BUOU": "Frasers L&C Tr",
    "TQ5": "Frasers Property",
    "E28": "Frencken",
    "D8DU": "FSL Trust",
    "F13": "Fu Yu",
    "508": "Fuji Offset",
    "BTY": "Full Apex",
    "AWK": "Fuxing China",
    "QS9": "G Invacom",
    "G41": "G K Goh",
    "5IG": "Gallant Venture",
    "41T": "GCCP",
    "5VP": "GDS Global",
    "G13": "Genting Sing",
    "RE4": "Geo Energy Res",
    "XJB": "GHY Culture",
    "595": "GKE",
    "586": "Global Dragon",
    "B73": "Global Inv",
    "BLW": "Global Palm Res",
    "AYN": "Global Testing",
    "E5H": "Golden Agri-Res",
    "AUE": "Golden Energy",
    "5PC": "Goodland",
    "G20": "GP Industries",
    "G50": "Grand Banks",
    "JLB": "Grand Venture",
    "G07": "Great Eastern",
    "Y06": "Green Build",
    "BLU": "GRP",
    "43A": "GS Hldg",
    "BDX": "GSH",
    "41F": "GSS Energy",
    "G11": "Guoan Intl",
    "F17": "GuocoLand",
    "AWS": "GYP Properties",
    "5AI": "H2G Green",
    "5VS": "Hafary",
    "BLH": "Hai Leck",
    "5VJ": "Halcyon Agri",
    "PH0": "Hatten Land",
    "H02": "Haw Par",
    "1B1": "HC Surgical",
    "40B": "HealthBank",
    "5NG": "Healthway Med",
    "5OR": "Heatec Jietong",
    "5DP": "Heeton",
    "5PD": "Hengyang Petro",
    "BTG": "HG Metal",
    "5GZ": "HGH",
    "5JK": "Hiap Hoe",
    "510": "Hiap Seng",
    "5PO": "Hiap Tong",
    "AVX": "HL Global Ent",
    "H13": "Ho Bee Land",
    "J2T": "Hock Lian Seng",
    "H20": "Hoe Leong",
    "H30": "Hong Fok",
    "CTO": "Hong Lai Huat",
    "H22": "Hong Leong Asia",
    "S41": "Hong Leong Fin",
    "H78": "HongkongLand USD",
    "BBP": "Hor Kew",
    "5EV": "Hosen",
    "H18": "Hotel Grand",
    "H12": "Hotel Royal",
    "BLS": "Hotung Inv",
    "P7VU": "HPH Trust SGD",
    "NS8U": "HPH Trust USD",
    "H15": "HPL",
    "CHZ": "HRnetGroup",
    "504": "HS Optimus",
    "41B": "Huationg Global",
    "H19": "Hwa Hong",
    "600": "Hyflux",
    "1J5": "Hyphens Pharma",
    "5I4": "ICP Ltd",
    "AIY": "IFAST",
    "I49": "IFS Capital",
    "Q0F": "IHH",
    "5HT": "Imperium Crown",
    "I4R": "Inch Kenneth",
    "RDR": "Incredible",
    "5JS": "Indofood Agri",
    "BOU": "Informatics",
    "M14": "InnoTek",
    "5GI": "Interra Resource",
    "KUO": "Intl Cement",
    "I06": "Intraco",
    "AZA": "IPC Corp",
    "42N": "IPS Securex",
    "8U7U": "IREIT Global EUR",
    "UD1U": "IREIT Global SGD",
    "I07": "ISDN",
    "40T": "ISEC",
    "I15": "Isetan",
    "5WF": "ISOTeam",
    "NXR": "iWOW Tech",
    "42C": "IX Biopharma",
    "J17": "Jackspeed",
    "J03": "Jadason",
    "5OI": "Japan Foods",
    "UD2": "Japfa",
    "C07": "Jardine C&C",
    "5PF": "Jason Marine",
    "FQ7": "Jasper Inv",
    "1J7": "Jawala",
    "BEW": "JB Foods",
    "1J4": "JEP",
    "EG0": "JES Intl",
    "C8R": "Jiutian Chemical",
    "J36": "JMH USD",
    "E9L": "Joyas Intl",
    "NHD": "Jubilee",
    "42R": "Jumbo",
    "K29": "Karin Tech",
    "1A0": "Katrina",
    "BNE": "Kencana Agri",
    "5TT": "Keong Hong",
    "A7RU": "Kep Infra Tr",
    "CMOU": "KepPacOakReitUSD",
    "BN4": "Keppel Corp",
    "AJBU": "Keppel DC Reit",
    "K71U": "Keppel Reit",
    "K03": "Khong Guan",
    "5G2": "Kim Heng",
    "1D0": "Kimly",
    "554": "King Wan",
    "5MZ": "KingsmenCreative",
    "5TI": "Kitchen Culture",
    "BJZ": "Koda",
    "K75": "Koh Bros",
    "5HV": "Koh Eco",
    "5I1": "KOP",
    "5VC": "Kori",
    "5OC": "Koyo Intl",
    "SK3": "KrisEnergy",
    "578": "KS Energy",
    "ER0": "KSH",
    "EB7": "KTL Global",
    "XCF": "KTMG",
    "LS9": "Leader Env",
    "JYEU": "Lendlease Reit",
    "W6TU": "Lendlease Reit A",
    "Q0X": "Ley Choon",
    "41O": "LHN",
    "GIH": "LHN Logistics",
    "BEI": "LHT",
    "L03": "Lian Beng",
    "1D3": "LifeBrandz",
    "BFT": "Lincotrade",
    "BAZ": "Lion Asiapac",
    "D5IU": "Lippo Malls Tr",
    "PRH": "Livingstone",
    "O6Z": "Lonza",
    "5IE": "Lorenzo Intl",
    "F1E": "Low Keng Huat",
    "ENV": "LS 2 Holdings",
    "L19": "Lum Chang",
    "5UA": "Luminor",
    "L09": "Lung Kee Bermuda",
    "BKK": "Luxking",
    "1H8": "LY Corp",
    "41S": "Magnus Energy",
    "M04": "Man Oriental USD",
    "BTOU": "ManulifeReit USD",
    "ME8U": "Mapletree Ind Tr",
    "M44U": "Mapletree Log Tr",
    "N2IU": "Mapletree PanAsia Com Tr",
    "5LY": "MarcoPolo Marine",
    "M12": "Maruwa Yen1k",
    "5OX": "Mary Chia",
    "M15": "Matex Intl",
    "5UF": "Maxi-Cash Fin",
    "Y3D": "MDR Limited",
    "5TN": "Medi Lifestyle",
    "OTX": "Medinex",
    "546": "Medtecs Intl",
    "5DS": "MegaChem",
    "SJY": "MeGroup",
    "TWL": "Memiontec Hldgs",
    "1H4": "Memories",
    "5NF": "Mencast",
    "5RF": "Mercurius",
    "DU4": "Mermaid Maritime",
    "5DX": "Meta Health",
    "V3M": "Metech Intl",
    "L02": "Metis Energy",
    "M01": "Metro",
    "MV4": "Mewah Intl",
    "M11": "MFG Integration",
    "5DD": "Micro-Mechanics",
    "5EN": "Midas",
    "CNE": "MindChamps",
    "M03": "Miyoshi",
    "1B0": "MM2 Asia",
    "5WJ": "MoneyMax Fin",
    "1V3": "Mooreast",
    "5WE": "Moya Asia",
    "40U": "MS Hldgs",
    "NPW": "MSC",
    "5QR": "MSM Intl",
    "M05": "MTQ",
    "AWZ": "Multi-Chem",
    "MF6": "Mun Siong Engg",
    "PJX": "Murata Yen1k",
    "F86": "MYP",
    "N4E": "Nam Cheong",
    "G0I": "Nam Lee Metal",
    "MZH": "Nanofilm",
    "5IF": "Natural Cool",
    "42D": "NauticAWT",
    "N01": "NeraTel",
    "5QY": "Net Pacific Fin",
    "CJLU": "NetLink NBN Tr",
    "BMT": "New Silkroutes",
    "N08": "New Toyo",
    "5FX": "New Wave",
    "5GF": "Nico Steel",
    "NIO": "NIO Inc. USD OV",
    "N32": "Nippecraft",
    "1G6": "No Signboard",
    "CGP": "Noble",
    "543": "Noel Gifts Intl",
    "N33": "Nomura Yen1k",
    "MR7": "Nordic",
    "NTA": "Novo Tellus SPAC",
    "N02": "NSL",
    "AZT": "NutryFarm",
    "O39": "OCBC Bank",
    "1B6": "Ocean Sky Intl",
    "579": "Oceanus",
    "584": "OEL",
    "HQU": "Oiltek",
    "KUX": "OIO",
    "S3N": "OKH Global",
    "5CF": "OKP",
    "VC2": "Olam Group",
    "5ML": "Old Chang Kee",
    "1H2": "Olive Tree",
    "5SY": "OneApex",
    "O08": "Ossia Intl",
    "OTS": "OTS Holdings",
    "LJ3": "OUE",
    "TS0U": "OUE Com Reit",
    "5WA": "OUE Lippo HC",
    "AJ2": "Ouhua Energy",
    "RQ1": "Overseas Edu",
    "5UX": "Oxley",
    "TVV": "OxPay Financial",
    "P11": "Pacific Andes",
    "P15": "Pacific Century",
    "T8V": "Pacific Radiance",
    "1C5": "Pacific Star Dev",
    "P36": "Pan Hong",
    "P52": "PanUnited",
    "O9E": "Parkson Retail",
    "C2PU": "ParkwayLife Reit",
    "596": "Pavillon",
    "IX2": "PEC",
    "PGS": "Pegasus SPAC",
    "BTM": "Penguin Intl",
    "BFK": "Pharmesis Intl",
    "YYN": "PlatoCapital",
    "BDA": "PNE Industries",
    "5BI": "Polaris",
    "5AE": "Pollux Prop",
    "BCY": "Powermatic Data",
    "OXMU": "Prime US ReitUSD",
    "BVQ": "Procurri",
    "583": "Progen",
    "OYY": "PropNex",
    "K6S": "Prudential USD",
    "DM0": "PSC Corporation",
    "QC7": "Q&M Dental",
    "Q01": "QAF",
    "BCV": "Qian Hu",
    "V8Y": "Quantum Health",
    "NR7": "Raffles Edu",
    "LUY": "Raffles Infrastructure",
    "BSL": "Raffles Medical",
    "1G1": "RE&S Hldg",
    "NEX": "Reclaims Global",
    "5EC": "Reenova Investment",
    "UV1": "Regal Intl",
    "I11": "Renaissance United",
    "QSD": "Resources Gbl",
    "RCU": "Revez",
    "5WH": "Rex Intl",
    "T13": "RH PetroGas",
    "RF1U": "RHT HealthTrust",
    "5G4": "Rich Capital",
    "AP4": "Riverstone",
    "M1GU": "Sabana Reit",
    "5DO": "Sakae",
    "E6R": "Samko Timber",
    "S56": "SamuderaShipping",
    "Y8E": "Samurai 2K",
    "1E3": "Sanli Env",
    "580": "Santak",
    "BRD": "Sapphire",
    "U77": "Sarine Tech",
    "CRPU": "Sasseur Reit",
    "S58": "SATS",
    "5PL": "SBI Offshore",
    "S61": "SBS Transit",
    "528": "Second Chance",
    "43B": "Secura",
    "U96": "Sembcorp Ind",
    "S51": "Sembcorp Marine",
    "5BS": "Sen Yue",
    "S69": "Serial System",
    "IW5": "Seroja Inv",
    "5EW": "Sevens Atelier",
    "S68": "SGX",
    "SES": "Shanaya",
    "AWM": "Shanghai Turbo",
    "S07": "Shangri-La HKD",
    "A78": "Shen Yao",
    "OV8": "Sheng Siong",
    "BKV": "Shenshan",
    "1F0": "Shopper360",
    "566": "SHS",
    "C6L": "SIA",
    "S59": "SIA Engineering",
    "BHK": "SIIC Environment",
    "STP": "Silkroad Nickel",
    "5CP": "Silverlake Axis",
    "URR": "Sim Leisure",
    "BKA": "Sin Heng Mach",
    "A26": "Sinarmas Land",
    "5UN": "Sincap",
    "S35": "Sing Inv & Fin",
    "FRQ": "Sing Paincare",
    "5WG": "SingaporeKitchen",
    "U06": "SingaporeLandGrp",
    "5IC": "SingHoldings",
    "5OT": "SingMedical",
    "S08": "SingPost",
    "S19": "SingShipping",
    "Z74": "Singtel",
    "Z77": "Singtel 10",
    "5HH": "Sinjia Land",
    "T4B": "Sino Grandness",
    "5EK": "SinoCloud",
    "C9Q": "Sinostar Pec",
    "5LE": "Sitra",
    "1J0": "SLB Dev",
    "Y45": "SMI Vantage",
    "S7P": "Soilbuild Const",
    "5MD": "Soon Lian",
    "5KI": "Soup Holdings",
    "A33": "Southern Arch",
    "BQP": "Southern Pkg",
    "QNS": "SouthernAlliance",
    "AWE": "SP Corp",
    "40E": "Spackman",
    "SK6U": "SPHREIT",
    "564": "Spindex Ind",
    "S23": "Spura Finance",
    "NC2": "Sri Trang Agro",
    "STG": "Sri Trang Gloves",
    "S63": "ST Engineering",
    "DRX": "ST Group Food",
    "H07": "Stamford Land",
    "S29": "Stamford Tyres",
    "P40U": "StarhillGbl Reit",
    "CC3": "StarHub",
    "S85": "Straco",
    "S20": "Straits Trading",
    "AAJ": "SunMoonFood",
    "5GD": "Sunpower",
    "S71": "Sunright",
    "581": "Sunrise Shares",
    "BKZ": "Suntar Eco-City",
    "T82U": "Suntec Reit",
    "BHU": "SUTL Enterprise",
    "BGK": "Swiber",
    "BEV": "Swing Media Tech",
    "5UO": "Sysma",
    "PA3": "TA",
    "500": "Tai Sin Electric",
    "42L": "Taka Jewellery",
    "5G3": "TalkMed",
    "T12": "Tat Seng Pkg",
    "VI2": "TC Auto",
    "T15": "TCIL HK$",
    "M1Z": "TEE Intl",
    "5OQ": "Teho Intl",
    "T41": "TeleChoice Intl",
    "Y92": "ThaiBev",
    "AWI": "Thakral",
    "E27": "The Place Hldg",
    "AGS": "TheHourGlass",
    "A50": "Thomson Medical",
    "T55": "TIH",
    "BFI": "Tiong Seng",
    "BQM": "Tiong Woon",
    "T14": "TJ DaRenTang USD",
    "BVA": "Top Glove",
    "S2D": "Tosei",
    "42F": "Totm Tech",
    "BCZ": "Travelite",
    "5AB": "Trek 2000 Intl",
    "42T": "Trendlines",
    "CYW": "TrickleStar",
    "5G9": "Tritech",
    "RC5": "Triyards",
    "KUH": "TSH",
    "T09": "TT Intl",
    "K1Q": "TTJ",
    "T24": "Tuan Sing",
    "540": "Tung Lok Rest",
    "BFU": "Tye Soon",
    "8K7": "UGHealthcare",
    "558": "UMS",
    "CHJ": "Uni-Asia Grp",
    "1F2": "Union Gas",
    "BLA": "Union Steel",
    "AZR": "United Food",
    "BGO": "Universal Res",
    "1D1": "UnUsUaL",
    "EH5": "UOA",
    "U11": "UOB",
    "U10": "UOB Kay Hian",
    "U13": "UOI",
    "U14": "UOL",
    "BRS": "USP Group",
    "ODBU": "UtdHampshReitUSD",
    "V2Y": "V2Y Corp",
    "WPC": "Vallianz",
    "T6I": "ValueMax",
    "BN2": "Valuetronics",
    "43E": "VCPlus",
    "V03": "Venture",
    "40N": "Versalink",
    "VT1": "Vertex SPAC",
    "BIP": "Vibrant Group",
    "BJD": "VibroPower",
    "WJP": "VICOM Ltd",
    "569": "Vicplas Intl",
    "OMK": "Vividthree",
    "WVJ": "Watches.com Ltd",
    "E3B": "Wee Hur",
    "BDR": "Willas-Array",
    "F34": "Wilmar Intl",
    "5F7": "Wilton Resources",
    "W05": "Wing Tai",
    "1A1": "Wong Fong Ind",
    "B49": "World Precision",
    "BQF": "XMH",
    "1F1": "Y Ventures",
    "BJV": "Yamada Green Res",
    "Z25": "Yanlord Land",
    "Y03": "Yeo Hiap Seng",
    "BPF": "YHI Intl",
    "5DM": "Ying Li Intl",
    "Z59": "Yoma Strategic",
    "BKX": "Yongmao",
    "AXB": "Yongnam",
    "T43": "Yunnan Energy",
    "AFC": "YuuZoo Networks",
    "YF8": "YZJ Fin Hldg",
    "SO7": "YZJ Shipbldg CNY",
    "BS6": "YZJ Shipbldg SGD",
    "BWM": "Zheneng Jinjiang",
    "5SR": "Zhongmin Baihui",
    "5EG": "Zhongxin Fruit",
    "40W": "ZICO Hldgs",
}
